### ISSUE TITLE
Missing example of how to use upgraded fastify-helmet with a style/script nonce

### ISSUE THREAD

**Issue by wolfejw86** [fastify/fastify-helmet#89] opened 2020-08-06 14:03 UTC
It used to be straightforward using a nonce with fastify-helmet by doing the following:
```js
fastify.register(helmet, {
  contentSecurityPolicy: {
    directives: {
      scriptSrc: [
        "'self'", 
        (req, res) => {
            // set nonce value on raw request
           const nonce = crypto.randomBytes(16).toString('base64');
           res.locals = { scriptNonce: nonce };

           return `'nonce-${nonce}'`;
        }
      ],
    },
  },
});
```

and then when rendering with something like point-of-view

```js
// inside route "handler"

reply.render('mypage', { nonce: reply.raw.locals.scriptNonce });
```
I get that the fastify api changed to using `.raw`, helmet package no longer supports a middleware function as part of a directive, and that this probably wasn't the best way to do this to begin with, but it did achieve the result as intended previously.
That being said, I feel like a CSP that uses nonced styles and scripts is very common and i feel like it is less clear than ever on how to achieve this with fastify-helmet.  It feels like it would almost be easier just using helmet by itself.  That being said, 

I figured the point of the fastify-helmet package is to make the ecosystem of fastify more robust by helping people easily achieve what they want.  I'm sure someone else has done this with the latest fastify-helmet package upgrade so I figured I'd reach out for help :)

First, can someone help me out by recommending a better approach since my "old way" no longer works 🤣  (yes I know it wasn't that great of a way anyways).

Second, what can we add (even if it's just some documentation) to help others with this issue?

Thanks in advance for any help!!

**Comment by mcollina** [comment] 2020-08-06 17:45
I don't have a clue. This is just a very lightweight wrapper on top of helmet itself, so `contentSecurityPolicy` is just passed through to them. As you can see in https://github.com/fastify/fastify-helmet/blob/5f86188019b827c6a223ca6154f8eda6cff1f09b/index.js#L7 we are just passing all the options through.

**Comment by mcollina** [comment] 2020-08-06 17:46
cc @EvanHahn

**Comment by wolfejw86** [comment] 2020-08-06 19:05
Here is an example of how you have to do nonces with the new version of helmet:

https://github.com/helmetjs/helmet/wiki/Conditionally-using-middleware

I'm probably missing something but I don't see how that's easy to do with the way this plugin wraps around helmet.  It's almost like I'd want to copy / paste the plugin index.js file into my code instead and just do that example how they have it.  That being said, it seems like a possible nice feature to be able to support dynamic nonces with a simpler api that fastify-helmet leverages.

**Comment by mcollina** [comment] 2020-08-06 20:56
The example should still work as before, the options are passed in https://github.com/helmetjs/helmet/blob/c01ad1e37c964df0108c37da4dd32af4630df95e/index.ts#L71.

**Comment by EvanHahn** [comment] 2020-08-06 20:59
Let me know if I can answer any questions here. I'll keep an eye on this issue but not a close one, so please @-mention me so I don't miss something.

**Comment by wolfejw86** [comment] 2020-08-07 14:00
it's not that the example doesn't work, it's that (i think) you have to go outside of this package to achieve a common use case with helmet (dynamically generated nonces).

**Comment by jsumners** [comment] 2020-08-07 15:58
So the issue here is that within your request handler you want to use `helmet.contentSecurityPolicy()` to set a unique value per request?

**Comment by wolfejw86** [comment] 2020-08-07 16:41
essentially yes.  I'm wondering if there's some way this package can help ease that though. as it stands, it seems like i might as well not install this package and just use the `helmet` package directly.  while that's certainly an option i just thought i saw potential for a small api to be baked into this package to help with that, something like `generateNonces: true` or allowing a function to generate nonces and decorate them on the reply object or something similar.

**Comment by jsumners** [comment] 2020-08-07 17:51
Unless I'm mistaken, the original intent of this plugin was to make it simple to apply some sane security oriented defaults to requests. So dynamic stuff like this wasn't in scope. But I think it might be worth adding an option like `enableCSPNonces: true` that adds:

```js
onRequest(request, response, next) {
  // generate nonce and add it to outgoing response
  next()
}
```

**Comment by wolfejw86** [comment] 2020-08-07 18:15
yes - my original reason for starting this issue was because i didn't understand the original scope / intent of this package + i was more unfamiliar with the helmet v4 upgrade.  From what I've gathered throughout this conversation, I would agree that it seems as though this package is just for the base case of security oriented things.  
I guess now it depends - does this package want to support generating nonces and storing them somewhere that makes sense on the outgoing response or just recommend that the user skip this package and use `helmet` directly.  If the former, I'd be happy to work on it.

**Comment by jsumners** [comment] 2020-08-07 18:45
The module is what the community makes it. If you'd like to work on a PR, that'd be fantastic.

**Comment by mcollina** [comment] 2020-08-08 12:59
Can you please upload a full example using the previous version of fastify-helmet? Something that can easily say yes/no if things works? A _failing_ unit test for that use case on this repo would also be very welcomed. There was no intention to break anything and all the unit tests where still passing (minus changes in helmet itself).

There should be no need to do `helmet.contentSecurityPolicy(cspOpts)` as  `app.register(require('fastify-helmet'), { contentSecurityPolicy: cspOpts })` apply the same options to the middlware. Given those are identical and the current code is functionally equivalent to what was there before, I do not understand what the problem is and I cannot advise for the line we should follow.

**Comment by wolfejw86** [comment] 2020-08-08 14:00
This repo did not introduce a breaking change - the underlying package helmet did so I don’t believe I can do what you’re asking.

**Comment by wolfejw86** [comment] 2020-08-08 14:50
Here is the working example I'm talking about demonstrating the use of dynamic nonces for inline scripts and inline styles (fairly common for server rendered apps)
```js
/**
 * To get this setup:
 * npm i point-of-view@3.x.x fastify@2.11.0 fastify-helmet@3.0.2
 */

"use strict";
const Fastify = require("fastify");
const helmet = require("fastify-helmet");
const fs = require("fs");
const path = require("path");
const pov = require("point-of-view");
const crypto = require("crypto");

const template = `
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Document</title>
  </head>
  <body>
  <div>script-nonce: {{scriptNonce}}</div>
  <div>style-nonce: {{styleNonce}}</div>

  <pre><code>
  // Script 1 - this one will not run because it has no nonce
  </code></pre>

  <pre><code id="script2">
  // Script 2 - this one will run in 2 seconds because it has a nonce
  </code></pre>
  </body>
  
  <script>
  // script 1 - will error
  alert('trying to run script 1');
  </script>

  <script nonce="{{scriptNonce}}">
  setTimeout(() => {
    alert('see this one works because of the nonce');
    script2.innerText = "Check the console to see the CSP error for script 1";
  }, 2000);
  </script>
</html>
`;

fs.writeFileSync(path.join(__dirname, "template.html"), template);

const startup = (fastify, opts, next) => {
  fastify.register(pov, {
    engine: {
      handlebars: require("handlebars"),
    },
  });
  fastify.register(helmet, {
    contentSecurityPolicy: {
      directives: {
        defaultSrc: ["'self'"],
        frameSrc: ["'self'"],
        styleSrc: [
          "'self'",
          (req, res) => {
            res.styleNonce = crypto.randomBytes(16).toString("base64");

            return `'nonce-${res.styleNonce}'`;
          },
        ],
        scriptSrc: [
          "'self'",
          (req, res) => {
            res.scriptNonce = crypto.randomBytes(16).toString("base64");

            return `'nonce-${res.scriptNonce}'`;
          },
        ],
      },
    },
    referrerPolicy: { policy: "same-origin" },
  });

  fastify.get("/", async (request, reply) => {
    reply.view("template.html", {
      scriptNonce: reply.res.scriptNonce,
      styleNonce: reply.res.styleNonce,
    });
  });
  next();
};

const fastify = Fastify();

fastify.register(startup);

fastify.listen(3000);
```

to see the issue - try to install the latest fastify versions for everything and use the same code as above.  I totally get that it is not the fastify plugin's fault for this breaking change to the underlying `helmet` package - but I am thinking it would be a nice thing for this package to support.

**Comment by wolfejw86** [comment] 2020-08-09 03:20
I took a pass at a possible implementation here - https://github.com/fastify/fastify-helmet/pull/90
Looking at it though, I'm not 100% convinced it's something this package would want to upkeep.  I would also be interested to hear other's opinions on the matter.

**Comment by mcollina** [comment] 2020-08-09 11:04
> I totally get that it is not the fastify plugin's fault for this breaking change to the underlying helmet package - but I am thinking it would be a nice thing for this package to support.

I still don't understand what the breaking change exactly is. I'll dig into it more via your example unless @EvanHahn beat me to it.

**Comment by EvanHahn** [comment] 2020-08-09 17:33
In Helmet 3, you could set a directive value with a function. For example:

```js
// ...
directives: {
  "default-src": [
    "'self'",
    (req, res) => `'nonce-${res.locals.cspNonce}'`,
  ],
}
// ...
```

This was removed in Helmet 4, but I think that was a mistake. I plan to re-add this soon and release an update. See https://github.com/helmetjs/helmet/issues/243 to follow my progress here.

**Comment by airhorns** [comment] 2020-09-14 15:04
`helmet` 4.1.0 has landed with support restored for the dynamic value style with those functions, but it's still kind of tricky to use with `fastify-helmet`. IMO the fastify way to do a CSP nonce would be something like:

```javascript
  server.decorateRequest("nonce", "");
  server.addHook("preValidation", async (request) => {
    request.nonce = crypto.randomBytes(16).toString("hex");
  });
  await server.register(FastifyHelmet, {
    contentSecurityPolicy: {
      directives: {
        "script-src": [
          "'self'",
          (req, res) => `'nonce-${req.nonce}'`,
        ],
      },
    },
  });
```

but since `helmet` itself is responsible for the invocation of the function there, the `req` is the `http.IncomingMessage`, not the `FastifyRequest`, so getting at the `nonce` is kind of tricky. I think it would be a better API for Fastify developers to get passed the `FastifyRequest` so they could use that nonce elsewhere in route handlers for rendering out script tags or what have you.

**Comment by EvanHahn** [comment] 2020-09-14 16:27
This feels like something that Helmet might want to fix, as it's not just a problem with Fastify. This would break with any framework that passed anything other than `http.IncomingMessage` and `http.ServerResponse` to Helmet. In Express, this might be `res.locals`. In Fastify, it might be `request.nonce`.

What happens when you do something like this?

```typescript
(req: FastifyRequest, res) => `'nonce-${req.nonce}'`
```

Does it compile properly?

**Comment by airhorns** [comment] 2020-09-14 17:02
No, it doesn't typecheck, because `fastify-helmet` is just using the helmet options type wholesale, see https://github.com/fastify/fastify-helmet/blob/master/index.d.ts#L4 . It's also purposefully passing the `http.IncomingMessage` into helmet in order for it to do it's thing, see https://github.com/fastify/fastify-helmet/blob/master/index.js#L9-L11 .

**Comment by EvanHahn** [comment] 2020-09-15 14:37
Hmm, okay. Because `req` and `reply` don't subclass `http.IncomingMessage` and `http.ServerResponse`, it seems like you may want to do something special for Helmet here—that's probably out of scope for Helmet, unfortunately.

**Comment by airhorns** [comment] 2020-10-21 13:05
Is there a way to get back to the `FastifyRequest` instance from the `http.IncomingMessage`? If that was true, we could map the helmet options to pass handlers in that play nice with Helmet and accept `http.IncomingMessage`s, and then make the jump back to the fastify objects and then pass those to the user handlers.

**Comment by airhorns** [comment] 2020-11-15 18:52
I don't think this is stale. Perhaps at a minimum we could adjust fastify-helmet's helmet dependency to exclude the newer helmets that this issue exists for?

**Comment by EvanHahn** [comment] 2020-11-18 15:25
I am not super familiar with this issue, but I believe this problem is not new. In other words, Helmet v3 and Helmet v4 should both have had this problem, I think.

I might be wrong about that because Helmet v3's type definitions were unofficial.

**Comment by wolfejw86** [comment] 2020-11-18 15:29
This was not an issue on v3 - the whole reason I created this issue was because of running into this problem upgrading to v4

**Comment by EvanHahn** [comment] 2020-11-18 15:34
Ah, okay—my bad. Carry on!

**Closed** 2021-03-05 09:44 UTC
