### ISSUE TITLE
type check failed when register the plugin

### ISSUE THREAD

**Issue by ianzone** [fastify/fastify-helmet#216] opened 2023-03-11 16:21 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.14.1

### Plugin version

10.1.0

### Node.js version

v18.12.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu 22.04.2

### Description

```
Argument of type 'FastifyHelmet' is not assignable to parameter of type 'FastifyPluginCallback<FastifyHelmetOptions, RawServerDefault, FastifyTypeProviderDefault, FastifyBaseLogger> | FastifyPluginAsync<...> | Promise<...> | Promise<...>'.
  Type 'FastifyHelmet' is not assignable to type 'FastifyPluginCallback<FastifyHelmetOptions, RawServerDefault, FastifyTypeProviderDefault, FastifyBaseLogger>'.
    Types of parameters 'instance' and 'instance' are incompatible.
      Type 'import("/home/ian/templates/lambda-nestify/node_modules/.pnpm/fastify@4.13.0/node_modules/fastify/types/instance").FastifyInstance<import("/home/ian/templates/lambda-nestify/node_modules/.pnpm/fastify@4.13.0/node_modules/fastify/types/utils").RawServerDefault, import("http").IncomingMessage, import("http").ServerRes...' is not assignable to type 'import("/home/ian/templates/lambda-nestify/node_modules/.pnpm/fastify@4.14.1/node_modules/fastify/types/instance").FastifyInstance<import("/home/ian/templates/lambda-nestify/node_modules/.pnpm/fastify@4.14.1/node_modules/fastify/types/utils").RawServerDefault, import("http").IncomingMessage, import("http").ServerRes...'.
        The types returned by 'withTypeProvider().after()' are incompatible between these types.
          Type 'import("/home/ian/templates/lambda-nestify/node_modules/.pnpm/fastify@4.13.0/node_modules/fastify/types/instance").FastifyInstance<import("/home/ian/templates/lambda-nestify/node_modules/.pnpm/fastify@4.13.0/node_modules/fastify/types/utils").RawServerDefault, import("http").IncomingMessage, import("http").ServerRes...' is not assignable to type 'import("/home/ian/templates/lambda-nestify/node_modules/.pnpm/fastify@4.14.1/node_modules/fastify/types/instance").FastifyInstance<import("/home/ian/templates/lambda-nestify/node_modules/.pnpm/fastify@4.14.1/node_modules/fastify/types/utils").RawServerDefault, import("http").IncomingMessage, import("http").ServerRes...'.
            Type 'FastifyInstance<RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, FastifyBaseLogger, Provider> & PromiseLike<...>' is not assignable to type 'FastifyInstance<RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, FastifyBaseLogger, Provider>'.
              Types of property 'decorateReply' are incompatible.
                Type '<T>(property: string | symbol, value: T extends (...args: any[]) => any ? (this: import("/home/ian/templates/lambda-nestify/node_modules/.pnpm/fastify@4.13.0/node_modules/fastify/types/reply").FastifyReply<import("/home/ian/templates/lambda-nestify/node_modules/.pnpm/fastify@4.13.0/node_modules/fastify/types/utils")...' is not assignable to type '<T>(property: string | symbol, value: T extends (...args: any[]) => any ? (this: import("/home/ian/templates/lambda-nestify/node_modules/.pnpm/fastify@4.14.1/node_modules/fastify/types/reply").FastifyReply<import("/home/ian/templates/lambda-nestify/node_modules/.pnpm/fastify@4.14.1/node_modules/fastify/types/utils")...'.
                  Types of parameters 'value' and 'value' are incompatible.
                    Type 'T extends (...args: any[]) => any ? (this: import("/home/ian/templates/lambda-nestify/node_modules/.pnpm/fastify@4.14.1/node_modules/fastify/types/reply").FastifyReply<import("/home/ian/templates/lambda-nestify/node_modules/.pnpm/fastify@4.14.1/node_modules/fastify/types/utils").RawServerDefault, ... 6 more ..., unk...' is not assignable to type 'T extends (...args: any[]) => any ? (this: import("/home/ian/templates/lambda-nestify/node_modules/.pnpm/fastify@4.13.0/node_modules/fastify/types/reply").FastifyReply<import("/home/ian/templates/lambda-nestify/node_modules/.pnpm/fastify@4.13.0/node_modules/fastify/types/utils").RawServerDefault, ... 6 more ..., unk...'.
                      Type 'T | ((this: FastifyReply<RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, ... 4 more ..., unknown>, ...args: Parameters<T>) => ReturnType<...>)' is not assignable to type 'T extends (...args: any[]) => any ? (this: FastifyReply<RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, ... 4 more ..., unknown>, ...args: Parameters<T>) => ReturnType<...> : T'.
                        Type 'T' is not assignable to type 'T extends (...args: any[]) => any ? (this: FastifyReply<RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, ... 4 more ..., unknown>, ...args: Parameters<T>) => ReturnType<...> : T'.
                          Type '(this: import("/home/ian/templates/lambda-nestify/node_modules/.pnpm/fastify@4.14.1/node_modules/fastify/types/reply").FastifyReply<import("/home/ian/templates/lambda-nestify/node_modules/.pnpm/fastify@4.14.1/node_modules/fastify/types/utils").RawServerDefault, ... 6 more ..., unknown>, ...args: Parameters<T>) => Re...' is not assignable to type '(this: import("/home/ian/templates/lambda-nestify/node_modules/.pnpm/fastify@4.13.0/node_modules/fastify/types/reply").FastifyReply<import("/home/ian/templates/lambda-nestify/node_modules/.pnpm/fastify@4.13.0/node_modules/fastify/types/utils").RawServerDefault, ... 6 more ..., unknown>, ...args: Parameters<T>) => Re...'.
                            The 'this' types of each signature are incompatible.
                              Type 'FastifyReply<RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, RouteGenericInterface, unknown, FastifySchema, FastifyTypeProviderDefault, unknown>' is missing the following properties from type 'FastifyReply<RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, RouteGenericInterface, unknown, FastifySchema, FastifyTypeProviderDefault, unknown>': cspNonce, helmetts(2345)
instance.d.ts(124, 17): This type parameter might need an `extends T extends (...args: any[]) => any ? (this: FastifyReply<RawServerDefault, http.IncomingMessage, http.ServerResponse<http.IncomingMessage>, ... 4 more ..., unknown>, ...args: Parameters<T>) => ReturnType<...> : T` constraint.
```

### Steps to Reproduce

https://docs.nestjs.com/security/helmet#use-with-fastify

**Comment by Uzlopak** [comment] 2023-03-11 17:24
Duplicate of #210

I also provided a PR in upstream helmet project. So it is a helmet issue.

**Closed by Uzlopak** 2023-03-11 17:24 UTC

**Comment by ianzone** [comment] 2023-04-29 01:58
@Uzlopak would you pls update the dependency since the upstream is updated?

**Comment by paynecodes** [comment] 2023-05-04 17:52
I've tried overriding `@fastify/helmet` depedency on helmet by forcing `helmet@6.1.5`. This issue remains.

**Comment by jhiode** [comment] 2023-06-27 19:33
I don't understand why but TypeScript (v4.9.5) is happy when I change the `FastifyHelmetOptions` type to this:
```diff
--- a/node_modules/@fastify/helmet/types/index.d.ts
+++ b/node_modules/@fastify/helmet/types/index.d.ts
@@ -27,9 +27,9 @@ declare namespace fastifyHelmet {
     helmet?: Omit<FastifyHelmetOptions, 'global'> | false;
   }
 
-  export interface FastifyHelmetOptions extends NonNullable<HelmetOptions> {
+  export type FastifyHelmetOptions = NonNullable<HelmetOptions> & {
     enableCSPNonces?: boolean,
     global?: boolean;
   }
 
   export const fastifyHelmet: FastifyHelmet
```
I couldn't reprouce this behaviour with the TS Playground though:
https://www.typescriptlang.org/play?ts=4.9.5#code/C4TwDgpgBAEhA2BbCwDyZgEsD2A7AzlALxQDeAUAJABm22A-AFxS4CuiARhAE5QA+UDnXgQAhrnIBfcuUy5gPaqIDG0AGKj8WaiDhIU6LHkIQAHgtwATQgDk8N1vHiiOIgDx7kaDDgIA+MnIoYMFRbiYWdi5uABogkI5RAC8Itk4eAG4pGWVjYChsH2NmDS1MHU8DIoJiQJCoWmxmAEY4+sTuZgAmOOlyXIJsEQA6eGwAcwAKQqMCAEosoA

Maybe that helps someone.

**Comment by Uzlopak** [comment] 2023-06-27 19:37
We actually fixed this upstream in helmet?! Do you still experience this issue with latest version of fastify-helmet?

**Comment by jhiode** [comment] 2023-06-28 10:26
Yes, we still have that problem. And we are on the latest version of fastify-helmet but not on the latest version of helmet though as that is limited by fastify-helmet:
https://github.com/fastify/fastify-helmet/blob/fe038ced8e2cc37d893c6240debce9f30bc5288b/package.json#L49

Btw, do you have a link to the fix for me?

**Comment by jhiode** [comment] 2023-06-28 10:33
Yes, we are on v6.2.0 and the error is also different.
```ts
  await fastify.register(helmet, {
    contentSecurityPolicy: false,
    crossOriginEmbedderPolicy: false,
    crossOriginOpenerPolicy: false,
    crossOriginResourcePolicy: false,
  });
```

```
No overload matches this call.
  Overload 1 of 3, '(plugin: FastifyPluginCallback<FastifyHelmetOptions, RawServerDefault, FastifyTypeProviderDefault, FastifyBaseLogger>, opts?: FastifyRegisterOptions<...> | undefined): FastifyInstance<...> & PromiseLike<...>', gave the following error.
    Argument of type '{ contentSecurityPolicy: boolean; crossOriginEmbedderPolicy: boolean; crossOriginOpenerPolicy: boolean; crossOriginResourcePolicy: boolean; }' is not assignable to parameter of type 'FastifyRegisterOptions<FastifyHelmetOptions> | undefined'.
      Object literal may only specify known properties, and 'contentSecurityPolicy' does not exist in type 'FastifyRegisterOptions<FastifyHelmetOptions>'.
  Overload 2 of 3, '(plugin: FastifyPluginAsync<FastifyHelmetOptions, RawServerDefault, FastifyTypeProviderDefault, FastifyBaseLogger>, opts?: FastifyRegisterOptions<...> | undefined): FastifyInstance<...> & PromiseLike<...>', gave the following error.
    Argument of type '{ contentSecurityPolicy: boolean; crossOriginEmbedderPolicy: boolean; crossOriginOpenerPolicy: boolean; crossOriginResourcePolicy: boolean; }' is not assignable to parameter of type 'FastifyRegisterOptions<FastifyHelmetOptions> | undefined'.
      Object literal may only specify known properties, and 'contentSecurityPolicy' does not exist in type 'FastifyRegisterOptions<FastifyHelmetOptions>'.
  Overload 3 of 3, '(plugin: FastifyPluginAsync<FastifyHelmetOptions, RawServerDefault, FastifyTypeProviderDefault, FastifyBaseLogger> | FastifyPluginCallback<...> | Promise<...> | Promise<...>, opts?: FastifyRegisterOptions<...> | undefined): FastifyInstance<...> & PromiseLike<...>', gave the following error.
    Argument of type '{ contentSecurityPolicy: boolean; crossOriginEmbedderPolicy: boolean; crossOriginOpenerPolicy: boolean; crossOriginResourcePolicy: boolean; }' is not assignable to parameter of type 'FastifyRegisterOptions<FastifyHelmetOptions> | undefined'.
      Object literal may only specify known properties, and 'contentSecurityPolicy' does not exist in type 'FastifyRegisterOptions<FastifyHelmetOptions>'
```

But I could create a new issue for this.

**Comment by Uzlopak** [comment] 2023-06-28 10:40
Hmm. Maybe, because of 

https://github.com/fastify/fastify-helmet/blob/fe038ced8e2cc37d893c6240debce9f30bc5288b/types/index.d.ts#L21

Maybe should be:
```typescript
type FastifyHelmet = FastifyPluginAsync<fastifyHelmet.FastifyHelmetOptions & {
  contentSecurityPolicy: typeof contentSecurityPolicy;
}>;
```

**Comment by Uzlopak** [comment] 2023-06-28 10:43
Please create a new issue and a repo where you provide a minimal reproducable example of the issue you experience.
