### ISSUE TITLE
using `@fastify/helmet` together with an extended `FastifyRequest` type leads to a type-error

### ISSUE THREAD

**Issue by jhiode** [fastify/fastify-helmet#223] opened 2023-06-28 11:06 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.18.0

### Plugin version

10.1.0

### Node.js version

v18.15.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13.4.1

### Description

By using `@fastify/helmet` together with extending the `FastifyRequest` type with custom attributes (as [described here](https://www.fastify.io/docs/latest/Reference/TypeScript/)) we get the following TS error:
```
error TS2769: No overload matches this call.
  Overload 1 of 3, '(plugin: FastifyPluginCallback<FastifyHelmetOptions, RawServerDefault, FastifyTypeProviderDefault, FastifyBaseLogger>, opts?: FastifyRegisterOptions<...> | undefined): FastifyInstance<...> & PromiseLike<...>', gave the following error.
    Argument of type '{ contentSecurityPolicy: boolean; crossOriginEmbedderPolicy: boolean; crossOriginOpenerPolicy: boolean; crossOriginResourcePolicy: boolean; }' is not assignable to parameter of type 'FastifyRegisterOptions<FastifyHelmetOptions> | undefined'.
      Object literal may only specify known properties, and 'contentSecurityPolicy' does not exist in type 'FastifyRegisterOptions<FastifyHelmetOptions>'.
  Overload 2 of 3, '(plugin: FastifyPluginAsync<FastifyHelmetOptions, RawServerDefault, FastifyTypeProviderDefault, FastifyBaseLogger>, opts?: FastifyRegisterOptions<...> | undefined): FastifyInstance<...> & PromiseLike<...>', gave the following error.
    Argument of type '{ contentSecurityPolicy: boolean; crossOriginEmbedderPolicy: boolean; crossOriginOpenerPolicy: boolean; crossOriginResourcePolicy: boolean; }' is not assignable to parameter of type 'FastifyRegisterOptions<FastifyHelmetOptions> | undefined'.
      Object literal may only specify known properties, and 'contentSecurityPolicy' does not exist in type 'FastifyRegisterOptions<FastifyHelmetOptions>'.
  Overload 3 of 3, '(plugin: FastifyPluginAsync<FastifyHelmetOptions, RawServerDefault, FastifyTypeProviderDefault, FastifyBaseLogger> | FastifyPluginCallback<...> | Promise<...> | Promise<...>, opts?: FastifyRegisterOptions<...> | undefined): FastifyInstance<...> & PromiseLike<...>', gave the following error.
    Argument of type '{ contentSecurityPolicy: boolean; crossOriginEmbedderPolicy: boolean; crossOriginOpenerPolicy: boolean; crossOriginResourcePolicy: boolean; }' is not assignable to parameter of type 'FastifyRegisterOptions<FastifyHelmetOptions> | undefined'.
      Object literal may only specify known properties, and 'contentSecurityPolicy' does not exist in type 'FastifyRegisterOptions<FastifyHelmetOptions>'.

73     contentSecurityPolicy: false,
```

Relates to https://github.com/fastify/fastify-helmet/issues/216#issuecomment-1610102613

### Steps to Reproduce

It should be enough to use the TypeScript (`v4.9.5`) with the following files:

`index.ts`:
```ts
import helmet from '@fastify/helmet';
import setupFastify from 'fastify';

const fastify = await setupFastify({ ... });

await fastify.register(helmet, {
  contentSecurityPolicy: false,
  crossOriginEmbedderPolicy: false,
  crossOriginOpenerPolicy: false,
  crossOriginResourcePolicy: false,
});
```

`tsconfig.json`:
```
{
  "compilerOptions": {
    "module": "ESNext",
    "moduleResolution": "node",
    "rootDir": "./",
    "target": "ES2019",
  },
}
```

`fastify.d.ts`:
```ts
import 'fastify';

declare module 'fastify' {
  interface FastifyRequest {
    startTime: number;
  }
}
```

**Comment by jhiode** [comment] 2023-06-28 11:20
Well, it seems to also fail without the `FastifyRequest` thingy.

**Comment by Uzlopak** [comment] 2023-06-28 11:20
Can you please provide a repository to clone with everything set up?

**Comment by jhiode** [comment] 2023-06-28 11:45
Sure, here you go: https://github.com/jhiode/fastify-helmet-test

**Comment by Uzlopak** [comment] 2023-06-28 11:58
Duplicate of #219 

Please use latest helmet 10.1.1, which covers the issue.

**Closed by Uzlopak** 2023-06-28 11:58 UTC

**Comment by Uzlopak** [comment] 2023-06-28 21:21
@jhiode 
Because of your remark regarding using helmet v6, we released today a new major version of fastify-helmet using latest helmet ;).
